### ISSUE TITLE
Add unbeatable mode

### ISSUE THREAD

**Issue by j-tesla** [j-tesla/tic-tac-toe#1]
Minmax algorithm works perfectly for games with a small number of turns like tic-tac-toe. The unbeatable mode or the hard mode can be implemented by it.

**Comment by gokulrajanpillai** [comment]
I would love to solve this. Please assign this to me

**Comment by j-tesla** [comment]
@gokulrajanpillai great!!
You may open a PR.

**Comment by gokulrajanpillai** [comment]
@j-tesla can you give me permission to make the branch for PR?

**Comment by j-tesla** [comment]
Fork, branch and PR. 
What permission do I need to give? @gokulrajanpillai

**Comment by gokulrajanpillai** [comment]
@j-tesla Thought I should create a branch directly from this repo (was the case for some other challenges). Thanks for clarifying this 👍
I have made the PR.
